os:
  - linux
  - osx

dist: xenial

language: rust

rust:
  - stable

cache: cargo

jobs:
  include:
    - stage: deploy
      if: tag IS present
      script: skip
      install: cargo build --verbose --release
      deploy:
        provider: releases
        edge: true
        token: $GITHUB_TOKEN
        file: target/release/accelerate

    - stage: deploy
      os: osx
      if: tag IS present
      script: skip
      install: cargo build --verbose --release
      deploy:
        provider: releases
        edge: true
        token: $GITHUB_TOKEN
        file: target/release/accelerate
