os:
  - linux
  - osx

dist: xenial

language: rust

rust:
  - stable

cache: cargo

jobs:
  include:
    - stage: deploy
      if: tag IS present
      script: cargo build --verbose --release
      after-script: 
        cp target/release/accelerate accelerate-linux
      deploy:
        provider: releases
        edge: true
        token: $GITHUB_TOKEN
        file: accelerate-linux

    - stage: deploy
      os: osx
      if: tag IS present
      script: cargo build --verbose --release
      after-script:
        cp target/release/accelerate accelerate-osx
      deploy:
        provider: releases
        edge: true
        token: $GITHUB_TOKEN
        file: accelerate-osx
